BabTeb/Models/ViewComponents/user/PackagesViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace BabTeb.Models.ViewComponents.user
{
    public class PackagesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            BLL.blpackage blp = new BLL.blpackage();
            return View("_packages", blp.read());
        }
    }
}

BabTeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BabTeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BabTeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BabTeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



            <div class="hero-slider-section position-relative">
                <div class="swiper hero-slider-container">
                    <div class="swiper-wrapper">
                        <div class="swiper-slide hero-slide3-item">
                            <div class="container">
                                <div class="hero-slide3-content">
                                    <h1 class="hero-slide3-title">فروشگاه طب سنتی بابونه</h1>
                                    <p class="hero-slide3-desc">هدف ما احیاء سبک زندگی سالم و اصیل ایرانی است.</p>
                                    <a class="hero-slide3-btn">موارد بیشتر</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @{
                 var q = new BLL.blintro();
                 var intro = q.read();
             }
             <div class="product-section section-padding-b">
                <div class="container">
            <div class="section-padding-b">
                <div class="container position-relative">
             @foreach (var item in intro)
            {
                    <img src="~/assets/images/photos/@item.pic" width="1170" height="550" alt="Image">
                    <a class="ht-video-popup" data-fancybox data-type="iframe" href="~/assets/videos/@item.videoIntro"><i class="icofont-play"></i></a>
            }
                </div>
            </div>
            </div>
            </div>

            @await Component.InvokeAsync("Packages")
           